[usb_modeswitch]

# failed to get it working :S
#source = "htmlparser"
#is_xml=true
#url = "https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-versions.xml"
#xpath = "concat(//xml/package[1]/release, '.', //xml/package[2]/release)"

# use xmlstarlet and curl for now
source = "cmd"
cmd = "curl -s https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-versions.xml | xmlstarlet sel -t -v 'concat(/xml/package[1]/release, \".\",  /xml/package[2]/release)'"
