version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "remove-useless-dep.patch",
]
SPDX-FileCopyrightText = "python-importlib-metadata contributors"
SPDX-License-Identifier = "Apache-2.0"
