version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "libmms-Remove-requires-glib2.0.patch",
]
SPDX-FileCopyrightText = "libmms contributors"
SPDX-License-Identifier = "LGPL-2.1-or-later"
