version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "dblatex-0.3.12-adjust-submodule-imports.patch",
    "dblatex-0.3.12-replace-imp-by-importlib.patch",
    "dblatex-0.3.12-script_path.patch",
]
SPDX-FileCopyrightText = "dblatex contributors"
SPDX-License-Identifier = "0BSD"
