version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "ab800bc.patch",
]
SPDX-FileCopyrightText = "python-sphinxcontrib-towncrier contributors"
SPDX-License-Identifier = "BSD-3-Clause"
