version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "*.conf",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "python-3.14.patch",
    "ruby-frozen-nil.patch",
    "subversion.rpath.fix.patch",
    "swig-4.4.patch",
]
SPDX-FileCopyrightText = "subversion contributors"
SPDX-License-Identifier = "Apache-2.0"
