version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Import-backflips-that-work-with-Python-3.12.patch",
]
SPDX-FileCopyrightText = "python-asn1crypto contributors"
SPDX-License-Identifier = "MIT"
