version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "*.appdata.xml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "lxterminal-fix-crash-on-close.patch",
    "lxterminal-transient-dialog.patch",
]
SPDX-FileCopyrightText = "lxterminal contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
