version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "pyxdg-python3.12.patch",
    "pyxdg-python3.14.patch",
    "pyxdg-python3.15.patch",
]
SPDX-FileCopyrightText = "pyxdg contributors"
SPDX-License-Identifier = "LGPL-2.0-only"
