version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-integer-types.patch",
]
SPDX-FileCopyrightText = "chmlib contributors"
SPDX-License-Identifier = "LGPL-2.1-or-later"
