[docbook-utils]
#source = "github"
#github = "docbook/dsssl"
#use_max_tag = true
#ignore = "SVNSNAPSHOT"

# source = "regex"
# regex = "docbook-utils-(\\d+.\\d+.\\d+)"
# url = "https://sourceware.org/ftp/docbook-tools/new-trials/SOURCES/"

source = "github"
github = "devexp-db/docbook-utils"
use_max_tag = true
prefix = "v"
