version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "remove-cov.patch",
    "use-system-certificates.patch",
]
SPDX-FileCopyrightText = "python-httplib2 contributors"
SPDX-License-Identifier = "MIT"
