version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-gpg-accept-subkeys-with-a-good-revocation-but-no-sel.patch",
    "0002-gpg-allow-import-of-previously-known-keys-even-witho.patch",
    "0003-tests-add-test-cases-for-import-without-uid.patch",
    "0004-gpg-drop-import-clean-from-default-keyserver-import-.patch",
    "0005-avoid-systemd-deprecation-warning.patch",
    "0006-Add-systemd-support-for-keyboxd.patch",
    "0007-Ship-sample-systemd-unit-files.patch",
    "0008-gpg-default-El-Gamal-to-3072-bit-keys.patch",
    "0009-gpg-Always-support-and-default-to-using-SHA-512.patch",
    "0010-gpg-Prefer-SHA-512-and-SHA-384-in-personal-digest-pr.patch",
    "0012-Disallow-compressed-signatures-and-certificates.patch",
    "0011-Avoid-simple-memory-dumps-via-ptrace.patch",
    "0013-ssh-agent-emulation-under-systemd-inject-SSH_AUTH_SO.patch",
    "0014-gpg-Sync-compliance-mode-cleanup-with-master.patch",
    "0015-gpg-emit-RSA-pubkey-algorithm-when-in-compatibility-.patch",
    "0016-gpg-Reintroduce-openpgp-as-distinct-from-rfc4880.patch",
    "0017-gpg-Emit-LibrePGP-material-only-in-compliance-gnupg.patch",
    "0018-gpg-gpgconf-list-report-actual-compliance-mode.patch",
    "0019-gpg-Default-to-compliance-openpgp.patch",
    "0020-gpg-Fix-newlines-in-Cleartext-Signature-Framework-CS.patch",
    "0021-Add-keyboxd-systemd-support.patch",
    "0022-Support-large-RSA-keygen-in-non-batch-mode.patch",
    "0023-gpg-Verify-Text-mode-Signatures-over-binary-Literal-.patch",
    "0024-gpg-Do-not-use-a-default-when-asking-for-another-out.patch",
    "gnupg-2.4-avoid_beta_warning.patch",
    "keyboxd.8",
]
SPDX-FileCopyrightText = "freepg/gnupg contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
