version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "libgpod-0.8.2-pkgconfig_overlinking.patch",
    "libgpod-0.8.3-implicit-int.patch",
    "libgpod-0.8.3-libplist-2.2.patch",
    "libgpod-0.8.3-libplist-2.3.patch",
    "libgpod-0.8.3-pkgconfig_sharp.patch",
    "libgpod-0.8.3-pointer-types.patch",
    "libgpod-playcounts.patch",
    "libgpod-snprintf.patch",
    "libgpod-udev.patch",
]
SPDX-FileCopyrightText = "libgpod contributors"
SPDX-License-Identifier = "LGPL-2.1-or-later"
