[perl-image-exiftool]
#source = "git"
#git = "https://github.com/exiftool/exiftool.git"

source = "regex"
url = "https://exiftool.org/history.html"
regex = 'production release is <a href="https://sourceforge.net/projects/exiftool/files/Image-ExifTool-(\d+\.\d+)'

# stable/production only
#source = "cpan"
#cpan = "Image-ExifTool"
