version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "wpa_supplicant_config",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Enable-TLSv1.0-by-default.patch",
    "0002-Disable-Werror-for-eapol_test.patch",
    "0003-Allow-legacy-renegotiation-to-fix-PEAP-issues-with-s.patch",
    "0004-Tweak-D-Bus-systemd-service-activation-configuration.patch",
    "0005-Add-IgnoreOnIsolate-yes-to-keep-wpa-supplicant-runni.patch",
    "0006-Add-reload-support-to-the-systemd-unit-files.patch",
    "0007-nl80211-add-extra-ies-only-if-allowed-by-driver.patch",
    "0008-Send-CTRL-EVENT-SIGNAL-CHANGE-message-to-control-interfaces-only.patch",
]
SPDX-FileCopyrightText = "wpa_supplicant contributors"
SPDX-License-Identifier = "BSD-3-Clause"
