version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "build-no-isolation.patch",
]
SPDX-FileCopyrightText = "python-setuptools contributors"
SPDX-License-Identifier = "MIT"
