[iana-etc]
source = "regex"
url = "https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml"
regex = "([0-9]{4}-[0-9]{2}-[0-9]{2})"
from_pattern = "([0-9]{4})-([0-9]{2})-([0-9]{2})"
to_pattern = "\\1\\2\\3"
